spring:
  datasource:
    url: jdbc:h2:mem:pms
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  error:
    include-message: always
    include-binding-errors: always
